workflows:
    android-workflow:
        name: Android Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          flutter: stable  
        scripts:
          - name: Get Flutter packages
            script: | 
              flutter packages pub get
          - name: Build AAB with Flutter
            script: | 
              flutter build appbundle --release
        artifacts:
          - build/**/outputs/**/*.aab
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log
        publishing:
          email:
            recipients:
              - burak.kurtarir35@gmail.com

